### ISSUE TITLE
ファイルアップロード・生成時の「読込中」や「処理中」 が表記がほしい

### ISSUE THREAD

**Issue by 1heisuzuki** [ry0y4n/ExifFrame#13]
です！

**Comment by ry0y4n** [comment]
:wakaru_of_the_year: :i_dont_wanna_think_css:

**Comment by ry0y4n** [comment]
![image](https://github.com/ry0y4n/ExifFrame/assets/38304912/2e58cf22-0d9f-4a1b-8e28-92fa89058022)

**Comment by ry0y4n** [comment]
一旦Closeします！

ぐるぐるをつけたいなどあれば言ってください．
