### ISSUE TITLE
iPad Safariにて大きめのサイズの画像を読み込ませると結果が表示されない

### ISSUE THREAD

**Issue by cha84rakanal** [ry0y4n/ExifFrame#6]
### 環境
iPad Pro 12.9 inch 4th gen
iPad OS 16.1
使用画像サイズ: 4000x6000
画像サイス: 4MB

### スクリーンショット
![IMG_2544](https://github.com/ry0y4n/ExifFrame/assets/22126355/40bdbe49-c285-4019-a11e-5a98b1fde191)

**Comment by ry0y4n** [comment]
手元のiPhoneではSafari・Chromeともに動作しました

## 環境

- iPhone 13 Pro
- iOS 16.1.1
- 使用サイズ：4000 * 6000
- 画像サイズ：3.5MB

**Comment by ry0y4n** [comment]
Chrome on iPadでは動作したみたいなので，iPad Safari依存の問題と推測しています

**Comment by ry0y4n** [comment]
かはー

[mobile Safari でも巨大な (HTML5)Canvas を画像ファイル出力するまで](https://qiita.com/D01/items/bf2a150fd6f817a289aa)

**Comment by ry0y4n** [comment]
<img width="813" alt="image" src="https://github.com/ry0y4n/ExifFrame/assets/38304912/f6423a27-82f8-42fe-be90-7e28bdad8107">

普通に，モバイル端末では画素数を落としてあげるのが幸せそうですね

**Comment by cha84rakanal** [comment]
![image](https://github.com/ry0y4n/ExifFrame/assets/22126355/ca1e9063-5506-4daa-9b4f-e08788178ac5)

> Canvas area exceeds the maximum limit (width * height > 16777216).

https://github.com/WebKit/WebKit/blob/9ff9626c9a61df3cb1ad38b6017fa6d3b7ee036f/Source/WebCore/html/CanvasBase.cpp#L149

**Comment by cha84rakanal** [comment]
https://github.com/ry0y4n/ExifFrame/pull/9 を作成した。

**Comment by ry0y4n** [comment]
https://github.com/ry0y4n/ExifFrame/pull/9 にて解決されたのでクローズします．[cha84rakanal](https://github.com/cha84rakanal)さんありがとうございました！
